#! /bin/sh

. ~/coloursconf

bspc config border_width	3
bspc config window_gap		8

bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config focus_by_distance	true

bspc config top_padding         40
bspc config left_padding        10
bspc config right_padding       10
bspc config bottom_padding      10

# Every time you create an instance of firefox, it will go to workspace 2
# bspc rule -a Firefox desktop=^2
bspc rule -a Steam floating=on 
bspc rule -a Steam desktop=^5 
bspc rule -a dota2 desktop=^7 

# List of all the desktops you want to use in this setup
echo "" > ~/bspwmOut
desktops=(I II III IV V VI VII VIII IX X)
screens=$(xrandr | grep -o ".* connected" | sed "s/ connected//")
echo "screens \"$screens\"" >> ~/bspwmOut
numScreens=$(echo "$screens" | wc -l)
echo "numScreens \"$numScreens\"" >> ~/bspwmOut
let desktopsPerMonitor=${#desktops[@]}
echo "desktops total \"$desktopsPerMonitor\"" >> ~/bspwmOut
let desktopsPerMonitor=$desktopsPerMonitor/$numScreens
echo "desktopsPerMonitor 2 \"$desktopsPerMonitor\"" >> ~/bspwmOut

let desktop=0
for screen in $(echo "$screens"); do
	printf "\tscreen \"$screen\"\n" >> ~/bspwmOut
	deskForMon=()
	let desk=0
	while [[ $desk -lt $desktopsPerMonitor ]]; do 
		deskForMon+=(${desktops[$desktop]}) 
		let desk+=1 
		let desktop+=1 
	done
	bspc monitor $screen -d ${deskForMon[@]}
	echo "$screen deskForMon \"${deskForMon[@]}\"" >> ~/bspwmOut
done
	
# # For my desktop setup
# if [[ $screens == *"HDMI-0 connected"* ]]; then
	# echo "Found HDMI-0"
	# bspc monitor HDMI-0 -d I II III IV V
# else
	# echo "Did not find HDMI-0"
# fi
# if [[ $screens == *"DVI-D-0 connected"* ]]; then
	# echo "Found DVI-D-0"
	# bspc monitor DVI-D-0 -d VI VII VIII IX X
# else
	# echo "Did not find DVI-D-0" 
# fi
# # For my lenovo laptop
# if [[ $screens == *"eDP1 connected"* ]]; then
	# echo "Found eDP1"
	# bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
# else
	# echo "Did not find eDP1"
# fi

bspc config focused_border_color		"$fg"
# Focused window on an unfocused desktop
bspc config active_border_color			"$bg"
bspc config normal_border_color			"$bg"
bspc config presel_border_color			"$gray"
bspc config urgent_border_color			"$red"

# Locked windows cannot be closed
bspc config focused_locked_border_color		"$fg"
bspc config active_locked_border_color		"$blue"
bspc config normal_locked_border_color		"$blue"
bspc config presel_locked_border_color		"$blue"

# Stickied windows stay in the focused desktop of the windows monitor
bspc config focused_sticky_border_color		"$fg"
bspc config active_sticky_border_color		"$green"
bspc config normal_sticky_border_color		"$green"
bspc config presel_sticky_border_color		"$green"

# Tries to maintain its tiling position and size
bspc config focused_private_border_color	"$fg"
bspc config active_private_border_color		"$magenta"
bspc config normal_private_border_color		"$magenta"
bspc config presel_private_border_color		"$magenta"
