#! /bin/sh

. ~/coloursconf

bspc config border_width	4
bspc config window_gap		8

bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config focus_by_distance	true

bspc config top_padding         50
bspc config left_padding        20
bspc config right_padding       20
bspc config bottom_padding      20

screens=$(xrandr)
# For my desktop setup
if [[ $screens == *"HDMI-0 connected"* ]];
then
	echo "Found HDMI-0"
	bspc monitor HDMI-0 -d I II III IV V
else
	echo "Did not find HDMI-0"
fi
if [[ $screens == *"DVI-D-0 connected"* ]]
then
	echo "Found DVI-D-0"
	bspc monitor DVI-D-0 -d VI VII VIII IX X
else
	echo "Did not find DVI-D-0" 
fi
# For my lenovo laptop
if [[ $screens == *"eDP1 connected"* ]]
then
	echo "Found eDP1"
	bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
else
	echo "Did not find eDP1"
fi

bspc config focused_border_color		"$fg"
# Focused window on an unfocused desktop
bspc config active_border_color			"$fg3"
bspc config normal_border_color			"$bg"
bspc config presel_border_color			"$gray"

bspc config urgent_border_color			"$redl"

# Locked windows cannot be closed
bspc config focused_locked_border_color		"$blue"
bspc config active_locked_border_color		"$bluel"
bspc config normal_locked_border_color		"$bluel"
bspc config presel_locked_border_color		"$bluel"

# Stickied windows stay in the focused desktop of the windows monitor
bspc config focused_sticky_border_color		"$aqua"
bspc config active_sticky_border_color		"$aqual"
bspc config normal_sticky_border_color		"$aqual"
bspc config presel_sticky_border_color		"$aqual"

# Tries to maintain its tiling position and size
bspc config focused_private_border_color	"$purple"
bspc config active_private_border_color		"$purplel"
bspc config normal_private_border_color		"$purplel"
bspc config presel_private_border_color		"$purplel"
