#!/usr/bin/env bash
#
# Takes no arguments, copies a hard-coded list of vim/nvim related
# configuration files to the home directory, creating the necessary parent
# directories if needed.

# TODO: update this warning to be accurate to this file, not `install-dotfiles`
######################################################################
#                              WARNING!                              #
######################################################################
#                                                                    #
#          This script may replace some files in your home           #
#    directory! This script takes all the files tracked by git in    #
#          the ~/dotfiles directory and copies them to ~/.           #
#                                                                    #
#   This includes important files such as .bashrc and .Xresources.   #
#                            BE PREPARED!                            #
#                                                                    #
######################################################################

FILES=(.vimrc .config/nvim/)

# The absolute path for the current directory. Strip the trailing "/" if there
# is one. There shouldn't be, but better safe than sorry.
source_dir=$(pwd | sed "s/\/$//")
dest_dir="~/"
commands_to_be_run=()

generate_command_list () {
	for i in "${!FILES[@]}"; do
		# If the current file path has a path of depth > 1 (i.e. if the path
		# specifies any parent directories)
		if [[ $(dirname "${FILES[$i]}") != "." ]]; then
			# [^\/] matches any char that is NOT "/"
			# file_parent_dir=$(echo "${FILES[$i]}" | sed "s/\/[^\/]*$//")

			# Create the parent directory for the file in `${dest_dir}`
			file_parent_dir=$(dirname "${FILES[$i]}")
			commands_to_be_run+=("mkdir -p \"${dest_dir}/${file_parent_dir}\"")
		fi

		# Once we have made any necessary parent directories in `${dest_dir}`
		# copy the file/dir from `${source_dir}` to `${dest_dir}`, and modify
		# its ownership to the current user
		commands_to_be_run+=("cp -Tria \"${source_dir}/${FILES[$i]}\" \"${dest_dir}/${FILES[$i]}\"")
		commands_to_be_run+=("chown $USER \"${dest_dir}/${FILES[$i]}\"")
	done
}

print_command_list () {
	# Print the command list
	for i in "${!commands_to_be_run[@]}"; do
		echo "${commands_to_be_run[$i]}"
	done
}

# Prompt the user for the destination directory
echo -n "What is the path to the destination directory? (enter=${dest_dir}) "
read -a ANSWER
if [[ ${ANSWER[*]} != "" ]]; then
	dest_dir="${ANSWER[*]}"
fi
# Strip the trailing "/" from `${dest_dir}` if there is one
dest_dir=$(echo "$dest_dir" | sed "s/\/$//")
printf "\n"

# Validate that the given destination directory path is valid
# If `$dest_dir` does not exist then exit early
if [[ ! -e "${dest_dir}" ]]; then
	printf "Specified destination directory does not exist: \"${dest_dir}\". Exiting...\n"
	exit 1
fi
# If `$dest_dir` is not a directory then exit early
if [[ ! -d "${dest_dir}" ]]; then
	printf "Specified destination directory is not a directory: \"${dest_dir}\". Exiting...\n"
	exit 1
fi
# If the user does not have permission to write to `$dest_dir` then exit early
if [[ ! -w "${dest_dir}" ]]; then
	printf "User does not have write permission for the specified destination directory: \"${dest_dir}\". Exiting...\n"
	exit 1
fi

generate_command_list
print_command_list
printf "\n"

echo -n "Would you like to run the above command list? [Y/n] (enter=Y): "
read -a ANSWER

if [[ ${ANSWER[*]} == "Y" || ${ANSWER[*]} == "" ]]; then
	# Execute all the commands in the command list
	for i in "${!commands_to_be_run[@]}"; do
		# Run the current command
		${commands_to_be_run[$i]}
	done
	printf "\n"
	printf "Attempted to copy files over.\n\n"
else
	printf "\n"
	printf "User chose not to copy over the files. Exiting...\n"
	exit 1
fi
