# Ayu (Light) (Converted from VSCode, customized by me)
[colors.primary]
foreground = "#5c6166"
background = "#f8f9fa"

[colors.cursor]
cursor = '#c7c7c7'
text = '#5c6166'

# Normal colors
[colors.normal]
# color 0
black= "#f8f9fa"
# color 1
red = "#ea6c6d"
# color 2
green = "#68b841"
# color 3
yellow = "#eca944"
# color 4
blue = "#3199e1"
# color 5
magenta = "#9e75c7"
# color 6
cyan = "#46ba94"
# color 7
white = "#5c6166"

# Bright colors
[colors.bright]
# color 8
black = "#c7c7c7"
# color 9
red = "#f07171"
# color 10
green = "#6cbf43"
# color 11
yellow = "#f2ae49"
# color 12
blue = "#399ee6"
# color 13
magenta = "#a37acc"
# color 14
cyan = "#4cbf99"
# color 15
white = "#313d46"

[font]
size = 15.0

[font.normal]
family = "RobotoMono"

# Keybinding for Ctrl+Shift+Enter for spawning a new terminal in the
# same directory.
[keyboard]
bindings = [
	{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[env]
# Pretend to be xterm for color schemes.
TERM = "xterm-256color"
